#pragma config(Sensor, in8,    lightSensor,         sensorReflection)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Wait for Light -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to wait until the lights around it come up to move forward for   *|
|*  1.5 seconds.  There is a two second pause at the beginning of the program.                        *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Lighting conditions change from place to place, so the value '200' may need to be changed   *|
|*        to better suit your environment.                                                            *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor  - Port 2     rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor  - Port 3     leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Analog - Port 8     lightSensor         VEX Light Sensor      Mounted facing up                 *|
\*-----------------------------------------------------------------------------------------------4246-*/


task emergencyStop()
{
	while(true)
	{
		if(vexRT[Btn7U]==1)
		{
			StopAllTasks();
		}
	}
}


const float BASEDIST = 486.12; // amount of degrees that wheel motors need to spin to travel 0.5m
void drive(int dist,bool bf){
	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;
	int backward_forward = (bf) ? (1):(-1);
	while(dist > abs(SensorValue[rightEncoder])){
		if(SensorValue[rightEncoder] == SensorValue[leftEncoder]) // If rightEncoder has counted the same amount as leftEncoder:
		{
			// Move Forward
			motor[rightMotor] = 50*backward_forward;		    // Right Motor is run at power level 80
			motor[leftMotor]  = 50*backward_forward;		    // Left Motor is run at power level 80
		}
		else if(abs(SensorValue[rightEncoder]) > abs(SensorValue[leftEncoder]))	// If rightEncoder has counted more encoder counts
		{
			// Turn slightly right
			motor[rightMotor] = 35*backward_forward;		    // Right Motor is run at power level 60
			motor[leftMotor]  = 50*backward_forward;		    // Left Motor is run at power level 80
		}
		else	// Only runs if leftEncoder has counted more encoder counts
		{
			// Turn slightly left
			motor[rightMotor] = 50*backward_forward;		    // Right Motor is run at power level 80
			motor[leftMotor]  = 35*backward_forward;		    // Left Motor is run at power level 60
		}
	}
}


void turn(float degrees, bool leftOrRight) {
	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;
	degrees = degrees * 3.9;
	while (degrees > abs(SensorValue[rightEncoder]) && degrees > abs(SensorValue[leftEncoder])) {
		if (leftOrRight == false) { //left
			motor[rightMotor] = 50;
			motor[leftMotor]  = -50;
			}
		else if (leftOrRight == true) { //right
			motor[rightMotor] = -50;
			motor[leftMotor]  = 50;
			}
		}
	}


task main()
{
	bool left = false;
	bool right = true;
	while(SensorValue(lightSensor) > 200) // While the ambient lightSensor reads a value greater than 200
	{
		if(SensorValue(sonarSensor) > 20  || SensorValue(sonarSensor) == -1)		// Loop while robot's Ultrasonic sensor is further than 20 inches away from an object  || (or) it is '-1'.  (-1 is the value returned when nothing is in it's visable range)
		{
		motor[rightMotor] = 63;			// Motor on port2 runs at half (63) power forward
		motor[leftMotor]  = 63;			// Motor on port3 runs at half (63) power forward
		}
		else
		{
		turn(5, left);
		}
	}
}
