#pragma config(Sensor, in1,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centreLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in4,    lightSensor,    sensorReflection)
#pragma config(Sensor, in5,    Potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl4,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  leftQuadEnc,    sensorQuadEncoder)
#pragma config(Sensor, dgtl10, rightQuadEnc,   sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex269, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                            - Moving Forward -                                      *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward for distance then backward then forward again   *|
|*  incrementing .5 m each time until 2.5 m                                                           *|
|*                                                                                                    *|
\*----------------------------------------------------------------------------------------------------*/

task driveMotors()
{
	while(true){
		motor[rightMotor] = 80;
		motor[leftMotor]  = 80;
		wait1Msec(800);
		motor[rightMotor] = -80;
		motor[leftMotor]  = -80;
		wait1Msec(800);
	}
}

task clawMotors()
{
	while(true){
		motor[clawMotor] = 20;
		wait1Msec(200);
		motor[clawMotor] = -20;
		wait1Msec(200);
	}
}

task armMotors()
{
	while(true){
		motor[armMotor] = -30;
		wait1Msec(200);
		motor[armMotor] = 70;
		wait1Msec(200);
	}
}

task main()
{

  StartTask(driveMotors);
  StartTask(armMotors);

  while(1!=0)
  {
    // Keep the program alive until pushButton is pressed
  }
	StopAllTasks();
}

// 4" diameter = 10.16 cm diameter
// 10.16 * pi = 31.9186 circumference
